[package]
name = "advent24"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.13.0"
rayon = "1.10.0"
regex = "1.11.1"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "benches"
harness = false
